### ISSUE TITLE
Test & document the consequences of `d2rl: True`

### ISSUE THREAD

**Issue by AugustDG** [TheNewtonCapstone/twip-isaac-sim#10]
Mostly because it was false in the original config & I haven't seen people use it. But definitely something that we need to test!

_Originally posted by @AugustDG in https://github.com/Sim2Capstone/twip-isaac-sim/pull/2#discussion_r1688441171_

From the paper that talks about it, it definitely seems like a no-brainer, so I wonder why people don't really use it...

**Comment by AugustDG** [comment]
Original paper here: https://sites.google.com/view/d2rl/home

**Comment by Shamiivan** [comment]
As a follow up, what was the end result? so we can close this issue?

**Comment by AugustDG** [comment]
The original creator doesn't know what the benefits really are + we're not using RL Games anymore, so yup! Bye Issue!
