### ISSUE TITLE
Create new IMU sensor from scratch

### ISSUE THREAD

**Issue by AugustDG** [TheNewtonCapstone/twip-isaac-sim#4]
That would eliminate the errors that we get for `wrong device for velocities tensor` and would give us more control over how the IMU reads data & processes it.

**Comment by Shamiivan** [comment]
Are there other people who have done something similar?

**Comment by AugustDG** [comment]
![Screenshot_20240708_214402_Discord.jpg](https://github.com/Sim2Capstone/twip-isaac-sim/assets/33916325/5873bcae-c38c-4798-a221-71c5b79f18e3)

Yup!
